/*
 * timer.c
 *
 *  	Created on: Jan 16, 2011
 *      Author: Cristian Axenie
 *      Functiile specifice lucrului cu Timer1 (16-bit)
 */

#include <avr/io.h>
#include <avr/interrupt.h>

unsigned char timer_table[8];
unsigned int OCR1;
short qtoc;
//functii specifice 
// implementare soft timer
void soft_timer(void);
// initializare timer1
void init_timer(void);
// functie decrementare 10ms
void decrement_10ms(void);
// rutina de tratare a intreruperilor de timer 
// in mod de operare output compare
ISR(TIMER1_COMPA_vect)
{
  // se aduna continutului registrului OCR valoarea 20000 pt a genera intrerupere la 20000*0.5us = 10ms
  qtoc = 1;// generare intrerupere
  OCR1 = (OCR1AH*256+OCR1AL)+20000;
  OCR1AH = (OCR1 & 0xFF00)>>8;
  OCR1AL = (OCR1 & 0xFF);
}

// implementeaza functionalitatea de timer software
void soft_timer(){

  if(qtoc==0)return;//dezactiveaza intreruperile
  qtoc=0;
  decrement_10ms();
}

// decrementeaza valoarea din tabela timerului
void decrement_10ms(){

  unsigned short i;

  for(i=0;i<8;i++){

    if(timer_table[i]!=0)
      timer_table[i]--;// decrementeaza timerul

  }

}
// Functie de initializare a timerului
void init_timer(void)
{ 
  // Code Generated by the Configuration Wizard
  // Timer/Counter 1 initialization
  // Clock source: System Clock
  // Clock value: 2000.000 kHz
  // Mode: Normal top=FFFFh
  // OC1A output: Discon.
  // OC1B output: Discon.
  // Noise Canceler: Off
  // Input Capture on Falling Edge
  // Timer 1 Overflow Interrupt: Off
  // Input Capture Inerrupt: Off
  // Compare A Match Interrupt: On
  // Compare B Match Interrupt: Off
  TCCR1A=0x00;// timer / counter control register A
  // timer / counter control register B,
  // the bit CS11 is set so CS12 CS11 CS10 = 0 1 0 and clkI/O/8 (From prescaler)
  TCCR1B=0x02;
  // nothing written in the counter
  TCNT1H=0x00;
  TCNT1L=0x00;
  // input capture diabled
  ICR1H=0x00;
  ICR1L=0x00;
  // output compare units A and B initially set to 0
  OCR1AH=0x00;
  OCR1AL=0x00;
  OCR1BH=0x00;
  OCR1BL=0x00;
}