/*
 * usart.c
 *
 *  	Created on: Jan 16, 2011
 *      Author: Cristian Axenie
 *      Functii specifice pentru lucrul cu modulul USART
 */

#include <avr/io.h>
#include <avr/interrupt.h>

// macrouri
#define RXB8 1
#define TXB8 0
#define UPE 2
#define OVR 3
#define FE 4
#define UDRE 5
#define RXC 7

// prototipuri functii
// initializare modul USART
void init_usart(void);
// functie pentru transmiterea unui caracter pe linia seriala
void send_char(char);
// functie de conversie binar la ascii 
void convert_to_ascii(unsigned char);
// functie care converteste 2 octeti hex in binar
unsigned char convert_to_bin(unsigned char, unsigned char);

// variabile globale
int txflag;//flag semnalizare TX
unsigned char txdata; // datele pentru transmisie
unsigned char lonib, hinib; // nibble low si high (1/2byte)

// rutina de tratare a intreruperilor pe transmisia USART
ISR(USART_TXC_vect){

  char status;
  status = UCSRA; // se p[reia statusul modului din registrul de stare UCSRA
  UDR = txdata;// se scrie data de transmis in registrul de date
  txflag = 1;// seteaza flagul de transmisie
}

// functie de conversie numar binar la 2 caractere ASCII hinib si lonib
void convert_to_ascii(unsigned char ch){

  hinib = (ch & 0xf0)>>4; // primul caracter
  lonib = (ch & 0x0f);	 // al doilea caracter

  if(hinib>9)hinib = hinib + '7';// daca este litera in baza 16
  else hinib = hinib + '0';	// daca este cifra in baza 16

  if(lonib>9)lonib = lonib + '7';// daca este litera in baza 16	
  else lonib = lonib + '0';// daca este cifra in baza 16

}

// functie care converteste doua caractere ASCII presupuse a fi digiti hex valizi intr-un octet binar
unsigned char convert_to_bin(unsigned char ch1, unsigned char ch2)
{

    unsigned char ch;

    if(ch1 <= '9') ch1=ch1&0x0f;

    else ch1= (ch1-7) & 0x0f;

    if(ch2 <= '9') ch2=ch2&0x0f;

    else ch2= (ch2-7) & 0x0f;

    ch=(ch1<<4)|ch2;

    return(ch);

}

// functie pentru transmiterea unui caracter pe linia seriala RS 232 
void send_char(char val){

  UDR = val;// se scrie valoare pentru a fi scrisa
  while(!(UCSRA & (1<<UDRE)));// cat timp sunt date in bufferul de TX

}

void init_usart(){
  // Code Generated by the Configuration Wizard
  // USART initialization
  UCSRA = 0x00;// USART control and status register A set to 0
  //USART control and status register B
  // Bit 6 – TXCIE: TX Complete Interrupt Enable is set
  // Bit 3 – TXEN: Transmitter Enable is set
  UCSRB = 0x48;// 01001000
  //USART control and status register C
  // Bit 7 – URSEL: Register Select is set
  // Bits 2:1 – UCSZ1:0: Character Size are set
  UCSRC = 0x86;// 10000110
  // USART baud rate register
  UBRRH = 0x00;
  // Trigger an immediate update of the baud rate prescaler
  UBRRL = 0x67;// 01100111
}